name: CI - ci-cd-practice

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build -x test

      - name: Run Unit Tests (JUnit 5)
        run: ./gradlew test

      - name: Build JAR
        run: ./gradlew build

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar

      - name: Notify Telegram on Success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TG_CHAT_ID }} \
            -d parse_mode=HTML \
            -d text="<b>✅ CI Passed</b>
          📁 <b>Repo:</b> ${{ github.repository }}
          👤 <b>By:</b> ${{ github.actor }}
          🌿 <b>Branch:</b> ${{ github.ref_name }}
          💬 <b>Message:</b> ${{ github.event.head_commit.message }}
          🔗 <a href='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'>View run</a>"

      - name: Notify Telegram on Failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TG_CHAT_ID }} \
            -d parse_mode=HTML \
            -d text="<b>❌ CI Failed</b>
          📁 <b>Repo:</b> ${{ github.repository }}
          👤 <b>By:</b> ${{ github.actor }}
          🌿 <b>Branch:</b> ${{ github.ref_name }}
          💬 <b>Message:</b> ${{ github.event.head_commit.message }}
          🔗 <a href='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'>View run</a>"